global: {}

ibm-platform-navigator-instance:
  ibmplatformnavigator:
    name: integration-navigator
    spec:
      license:
        accept: true
        license: L-RJON-CJR2RX
      mqDashboard: true
      version: 2022.4.1
      replicas: 2   